# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: 定时脚本

on:
  schedule:
    - cron: "45 14 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '16.14.0'
      - name: Install and Build 🔧
        run: |
          npm install
          node ./szrmb.js
